# Site settings
title: lab.jacksay.com
email: stephane.bouvry@unicaen.fr
description: > # Note de développement d'un développeur.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: studiojacksay
github_username:  jacksay
author: Jacksay
paginate: 5

# Build settings
markdown: redcarpet
highlighter: pygments

# Collection
collections:
    slides:
        output: true
defaults:
  - scope:
      path: ""
      type: slides
    values:
      layout: slide
